### ISSUE TITLE
Wish: Recreate PDF at click on download button

### ISSUE THREAD

**Issue by Support-Green-IT-Solutions** [modoboa/modoboa-pdfcredentials#37]
Hi, 
Sometimes, PDF are not readable after account creation or update. Is it possible to recreate PDF just before download ?

**Comment by tonioo** [comment]
@Support-Green-IT-Solutions What do you mean by unreadable?

**Comment by Support-Green-IT-Solutions** [comment]
In web browser or directly in PDF reader, an error occurred when opening the PDF like in these screenshots
![image](https://user-images.githubusercontent.com/44780912/103272836-24814e80-49be-11eb-8ee4-8a98f76b8eb8.png)
![image](https://user-images.githubusercontent.com/44780912/103272908-5397c000-49be-11eb-9526-53379a2fe19f.png)
