### ISSUE TITLE
pdfcredentials - how is it supposed to work?

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa-pdfcredentials#7]
How is this supposed to work?  I can see when I initially create a user I get the option to  download a pdf file with the credentials.  Once i have downloaded the PDF file the option to download once more is no longer presented.  Is that the way it is supposed to work?

**Comment by oconshaw** [comment]
Also, since the passwords are encrypted, how are you able to get the password to present in the PDF file?  I thought it was a one way hash?

**Comment by tonioo** [comment]
PDF files are automatically deleted after the first download but that's a behaviour you can change. Look at global parameters (Modoboa > Parameters > PDF credentials). And the PDF is generated just before the password is encrypted.

**Comment by oconshaw** [comment]
Oh, I have looked at that a dozen times and didn't' make the connection.  Thanks!
Does that work when one seeds the database with identities from a csv file import?  I think it does not.  Maybe it would work if I tell the import to encrypt the password on import.  I haven't tried that yet.

**Comment by tonioo** [comment]
Documents should be generated when you import from a csv file.

**Comment by tonioo** [comment]
@oconshaw Have you checked import?

**Comment by tonioo** [comment]
@oconshaw FYI, it will work if you crypt passwords during the import.
